### ISSUE TITLE
Installation instructions for Linux should mention node BLE privileges

### ISSUE THREAD

**Issue by jdpigeon** [OpenBCI/OpenBCI_NodeJS_Ganglion#32]
Just set this up today on my Linux and ran into an issue when trying to run a script that used both openbci-ganglion and python-shell.

the noble dependency prompted me to run the script as sudo to access where noble was prompting me to run the node script as sudo in order to access BLE privileges. However, this caused a mess in the python scripts because of the whole complicated [*nix user/root different python path issue](https://stackoverflow.com/questions/25387374/why-are-modules-in-pythonpath-not-found-when-the-containing-directory-is-part-of).

The fix ended up being following the [instructions](https://github.com/sandeepmistry/noble#running-on-linux) on the noble README to allow node to access BLE privileges without sudo.

Perhaps that simple fix should be added to the README here to avoid tripping up future Linux users.

I'm happy to make the PR if you guys want

**Comment by aj-ptw** [comment]
Yes could you PR? Thanks so much!
